apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
    app: {{ .Values.serviceName }}
  name: jvb-udp
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - port: 30300
    name: video-bridge
    protocol: UDP
    targetPort: 30300
    nodePort: 30300
  selector:
    app: {{ .Values.serviceName }}
