---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project={{ .Values.serviceName }}&var-version={{ .Values.imageTag }}
  labels:
    app: {{ .Values.serviceName }}
    provider: fabric8
    version: "{{ .Values.imageTag }}"
    group: net.fhirbox.pegacorn
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.numOfPods | default 2 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
      provider: fabric8
      group: net.fhirbox.pegacorn
  template:
    metadata:
      annotations:
        fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project={{ .Values.serviceName }}&var-version={{ .Values.imageTag }}
      labels:
        app: {{ .Values.serviceName }}
        provider: fabric8
        version: "{{ .Values.imageTag }}"
        group: net.fhirbox.pegacorn
        date: "{{ date "20060102-150405" .Release.Time }}"
    spec:
      volumes:
      - name: prosody-certs
        hostPath:
          path: {{ .Values.hostPathProsody }}
      - name: nginx-certs
        hostPath:
          path: {{ .Values.hostPathNginx }}
      containers:
      # Configure jicofo
        - name: jicofo
          image: {{ .Values.dockerRepo }}pegacorn-communicate-jitsi-jicofo:{{ .Values.imageTag }}            
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash","-c","service jicofo start"]
          env:
            - name: XMPP_SERVER
              value: "127.0.0.1"
            - name: XMPP_DOMAIN
              value: pegacorn-communicate-jitsi.site-a
            - name: XMPP_AUTH_DOMAIN
              value: auth.pegacorn-communicate-jitsi.site-a
            - name: XMPP_MUC_DOMAIN
              value: muc.pegacorn-communicate-jitsi.site-a
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.pegacorn-communicate-jitsi.site-a
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: Australia/Sydney
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
            # - name: JICOFO_HOSTNAME
            #   value: pegacorn-communicate-jitsi.site-a
            # - name: JICOFO_AUTH_DOMAIN
            #   value: auth.pegacorn-communicate-jitsi.site-a      
      # Configure prosody
        - name: prosody
          image: {{ .Values.dockerRepo }}pegacorn-communicate-jitsi-prosody:{{ .Values.imageTag }}            
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          ports:
          - containerPort: 5222
            name: xmpp-client
            protocol: TCP
          - containerPort: 5269
            name: xmpp-server
            protocol: TCP
          - containerPort: 5347
            name: jitsi-jicofo
            protocol: TCP
          - containerPort: 5280
            name: jitsi-bosh
            protocol: TCP
          - containerPort: 5281
            name: bosh-https
            protocol: TCP
          volumeMounts:
          - name: prosody-certs
            mountPath: /config/certs
          env:
            - name: XMPP_DOMAIN
              value: pegacorn-communicate-jitsi.site-a
            - name: XMPP_AUTH_DOMAIN
              value: auth.pegacorn-communicate-jitsi.site-a
            - name: XMPP_MUC_DOMAIN
              value: muc.pegacorn-communicate-jitsi.site-a
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.pegacorn-communicate-jitsi.site-a
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: Australia/Sydney
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: PUBLIC_URL
              value: https://pegacorn-communicate-jitsi.site-a
      # Configure nginx
        - name: nginx
          image: {{ .Values.dockerRepo }}pegacorn-communicate-jitsi-web:{{ .Values.imageTag }}            
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }} 
          volumeMounts:
          - name: nginx-certs
            mountPath: /config/keys         
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
          env:
            - name: XMPP_SERVER
              value: "127.0.0.1"
            - name: JICOFO_AUTH_USER
              value: focus
            - name: XMPP_DOMAIN
              value: pegacorn-communicate-jitsi.site-a
            - name: XMPP_AUTH_DOMAIN
              value: auth.pegacorn-communicate-jitsi.site-a
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.pegacorn-communicate-jitsi.site-a
            - name: XMPP_BOSH_URL_BASE
              value: http://pegacorn-communicate-jitsi.site-a:5280
            - name: XMPP_MUC_DOMAIN
              value: muc.pegacorn-communicate-jitsi.site-a
            - name: TZ
              value: Australia/Sydney
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: PUBLIC_URL
              value: https://pegacorn-communicate-jitsi.site-a
      # Configure jvb
        - name: jvb
          image: {{ .Values.dockerRepo }}pegacorn-communicate-jitsi-jvb:{{ .Values.imageTag }}            
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash","-c","service jitsi-videobridge2 start"]
          env:
            - name: XMPP_SERVER
              value: "127.0.0.1"
            - name: DOCKER_HOST_ADDRESS
              value: "192.168.0.10"
            - name: XMPP_DOMAIN
              value: pegacorn-communicate-jitsi.site-a
            - name: XMPP_AUTH_DOMAIN
              value: auth.pegacorn-communicate-jitsi.site-a
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.pegacorn-communicate-jitsi.site-a
            # - name: JVB_STUN_SERVERS
            #   value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302 (Replace with Pegacorn stun server)
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_PORT
              value: "30300"
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: Australia/Sydney
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
            - name: PUBLIC_URL
              value: https://pegacorn-communicate-jitsi.site-a
