---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if (.Values.dnsEntry) }}
    # From https://docs.microsoft.com/en-us/azure/aks/internal-lb#create-an-internal-load-balancer
    service.beta.kubernetes.io/azure-load-balancer-internal: "{{ .Values.loadBalancerInternal | default true }}"
#    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.dnsEntry }}
    # From https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/rfc2136.md
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dnsEntry }}
    {{- end }}    
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    app: {{ .Values.serviceName }}
    provider: fabric8
    version: "{{ .Values.imageTag }}"
    group: net.fhirbox.pegacorn
  name: {{ .Values.serviceName }}
spec:
  ports:  
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: xmpp-client
    port: 5222
    protocol: TCP
    targetPort: 5222
  - name: xmpp-server
    port: 5269
    protocol: TCP
    targetPort: 5269
  - name: jitsi-bosh
    port: 5280
    protocol: TCP
    targetPort: 5280
  - name: bosh-https
    port: 5281
    protocol: TCP
    targetPort: 5281
  - name: jitsi-jicofo
    port: 5347
    protocol: TCP
    targetPort: 5347    
  selector:
    app: {{ .Values.serviceName }}
    provider: fabric8
    group: net.fhirbox.pegacorn
  type: {{ .Values.serviceType | default "LoadBalancer" }}
  {{- if (.Values.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  {{- end }}

